import type { Metadata } from "next";
import "./globals.css";

import {inter} from '@/app/ui/fonts'
import {ThemeProvider} from "@/components/theme-provider";
import HeaderWithSidebar from "@/app/ui/header-with-sidenav";
import {Toaster} from "@/components/ui/toaster";
import {SessionProvider} from "next-auth/react";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-background`}
      >
      <SessionProvider>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem

          >
              <HeaderWithSidebar>
                  {children}
              </HeaderWithSidebar>
              <Toaster/>
          </ThemeProvider>
      </SessionProvider>

      </body>
    </html>
  );
}
